<a href="https://colab.research.google.com/github/kamlesh4817/pytorch-examples/blob/main/colab-interactive-sheets-example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import auth
from google.auth import default
import gspread
from google.colab import sheets
import pandas as pd
import numpy as np
from vega_datasets import data
df = data.us_state_capitals()
df

           lon        lat           state            city
0   -86.279118  32.361538         Alabama      Montgomery
1  -134.419740  58.301935          Alaska          Juneau
2  -112.073844  33.448457         Arizona         Phoenix
3   -92.331122  34.736009        Arkansas     Little Rock
4  -121.468926  38.555605      California      Sacramento
5  -104.984167  39.739167        Colorado          Denver
6   -72.677000  41.767000     Connecticut        Hartford
7   -75.526755  39.161921        Delaware           Dover
8   -84.272770  30.451800         Florida     Tallahassee
9   -84.390000  33.760000         Georgia         Atlanta
10 -157.826182  21.308950          Hawaii        Honolulu
11 -116.237651  43.613739           Idaho           Boise
12  -89.650373  39.783250        Illinois     Springfield
13  -86.147685  39.790942         Indiana    Indianapolis
14  -93.620866  41.590939            Iowa      Des Moines
15  -95.690000  39.040000          Kansas          Topeka
16  -84.863110  38.197274        Kentucky       Frankfort
17  -91.140229  30.458090       Louisiana     Baton Rouge
18  -69.765261  44.323535           Maine         Augusta
19  -76.501157  38.972945        Maryland       Annapolis
20  -71.027500  42.235200   Massachusetts          Boston
21  -84.546700  42.733500        Michigan         Lansing
22  -93.094000  44.950000       Minnesota      Saint Paul
23  -90.207000  32.320000     Mississippi         Jackson
24  -92.189283  38.572954        Missouri  Jefferson City
25 -112.027031  46.595805         Montana          Helena
26  -96.675345  40.809868        Nebraska         Lincoln
27 -119.753877  39.160949          Nevada     Carson City
28  -71.549127  43.220093   New Hampshire         Concord
29  -74.756138  40.221741      New Jersey         Trenton
30 -105.964575  35.667231      New Mexico        Santa Fe
31  -73.781339  42.659829        New York          Albany
32  -78.638000  35.771000  North Carolina         Raleigh
33 -100.779004  48.813343    North Dakota        Bismarck
34  -83.000647  39.962245            Ohio        Columbus
35  -97.534994  35.482309        Oklahoma   Oklahoma City
36 -123.029159  44.931109          Oregon           Salem
37  -76.875613  40.269789    Pennsylvania      Harrisburg
38  -71.422132  41.823550    Rhode Island      Providence
39  -81.035000  34.000000  South Carolina        Columbia
40 -100.336378  44.367966    South Dakota          Pierre
41  -86.784000  36.165000       Tennessee       Nashville
42  -97.750000  30.266667           Texas          Austin
43 -111.892622  40.754700            Utah  Salt Lake City
44  -72.571940  44.266390         Vermont      Montpelier
45  -77.460000  37.540000        Virginia        Richmond
46 -122.893077  47.042418      Washington         Olympia
47  -81.633294  38.349497   West Virginia      Charleston
48  -89.384444  43.074722       Wisconsin         Madison
49 -104.802042  41.145548         Wyoming        Cheyenne

In [10]:
import altair as alt
alt.renderers.enable('colab')

RendererRegistry.enable('colab')

In [4]:
sheet = sheets.InteractiveSheet(title="State Captitals", include_column_headers=True, df=df)
df2 = sheet.as_df()
df2

https://docs.google.com/spreadsheets/d/1qGiGesGXrP3CCoGH3NVtruV_QmZNRmkQ9gPH8HKPcVw/edit#gid=0

            lon         lat           state            city
0    -86.279118   32.361538         Alabama      Montgomery
1    -134.41974   58.301935          Alaska          Juneau
2   -112.073844   33.448457         Arizona         Phoenix
3    -92.331122   34.736009        Arkansas     Little Rock
4   -121.468926   38.555605      California      Sacramento
5   -104.984167  39.7391667        Colorado          Denver
6       -72.677      41.767     Connecticut        Hartford
7    -75.526755   39.161921        Delaware           Dover
8     -84.27277     30.4518         Florida     Tallahassee
9        -84.39       33.76         Georgia         Atlanta
10  -157.826182    21.30895          Hawaii        Honolulu
11  -116.237651   43.613739           Idaho           Boise
12   -89.650373    39.78325        Illinois     Springfield
13   -86.147685   39.790942         Indiana    Indianapolis
14   -93.620866   41.590939            Iowa      Des Moines
15       -95.69       39.04          Kansas          Topeka
16    -84.86311   38.197274        Kentucky       Frankfort
17   -91.140229    30.45809       Louisiana     Baton Rouge
18   -69.765261   44.323535           Maine         Augusta
19   -76.501157   38.972945        Maryland       Annapolis
20     -71.0275     42.2352   Massachusetts          Boston
21     -84.5467     42.7335        Michigan         Lansing
22      -93.094       44.95       Minnesota      Saint Paul
23      -90.207       32.32     Mississippi         Jackson
24   -92.189283   38.572954        Missouri  Jefferson City
25  -112.027031   46.595805         Montana          Helena
26   -96.675345   40.809868        Nebraska         Lincoln
27  -119.753877   39.160949          Nevada     Carson City
28   -71.549127   43.220093   New Hampshire         Concord
29   -74.756138   40.221741      New Jersey         Trenton
30  -105.964575   35.667231      New Mexico        Santa Fe
31   -73.781339   42.659829        New York          Albany
32      -78.638      35.771  North Carolina         Raleigh
33  -100.779004   48.813343    North Dakota        Bismarck
34   -83.000647   39.962245            Ohio        Columbus
35   -97.534994   35.482309        Oklahoma   Oklahoma City
36  -123.029159   44.931109          Oregon           Salem
37   -76.875613   40.269789    Pennsylvania      Harrisburg
38   -71.422132    41.82355    Rhode Island      Providence
39      -81.035          34  South Carolina        Columbia
40  -100.336378   44.367966    South Dakota          Pierre
41      -86.784      36.165       Tennessee       Nashville
42       -97.75   30.266667           Texas          Austin
43  -111.892622     40.7547            Utah  Salt Lake City
44    -72.57194    44.26639         Vermont      Montpelier
45       -77.46       37.54        Virginia        Richmond
46  -122.893077   47.042418      Washington         Olympia
47   -81.633294   38.349497   West Virginia      Charleston
48   -89.384444   43.074722       Wisconsin         Madison
49  -104.802042   41.145548         Wyoming        Cheyenne

In [9]:
import altair as alt

# Create a base map of the US states
states = alt.topo_feature(data.us_10m.url, 'states')

# Define the base chart for the map
base = alt.Chart(states).project('albers').properties(
    title='US State Capitals'
)

# Create the state borders layer
state_borders = base.mark_geoshape(
    fill='lightgray',
    stroke='white'
)

# Create the capitals layer
capitals = alt.Chart(df2).mark_circle().encode(
    longitude=alt.X('lon', type='quantitative'),
    latitude=alt.Y('lat', type='quantitative'),
    size=alt.value(50), # Adjust size of points
    color=alt.value('red'), # Color the points red
    tooltip=['state', 'city'] # Add tooltips for state and city
).properties(
    title='State Capitals'
)

# Combine the state borders and capitals layers and set overall chart size
map_chart = (state_borders + capitals).properties(
    width=800,  # Set a larger width
    height=500  # Set a larger height
).interactive() # Add interactivity for zoom and pan

# Display the map
map_chart

alt.LayerChart(...)